### 조회
GET http://localhost:8080/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMTU5NjI1LCJleHAiOjE3MDExNjE0MjUsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJElPdlVoOFJqdHRxMTRaSjhSYVBqUnVoN2FKa1ZDQVdMSHguSTl6UFJCbjl6dkZHOVg1Ykt1IiwibmFtZSI6Im9ramFlb29rIn0.TVvMcujy3_EQDJQcg0CXFVeQpJ5_rF0V83tvcs84dx4

### 삭제
DELETE http://localhost:8080/carts/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMTU2MTc1LCJleHAiOjE3MDExNTc5NzUsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJElPdlVoOFJqdHRxMTRaSjhSYVBqUnVoN2FKa1ZDQVdMSHguSTl6UFJCbjl6dkZHOVg1Ykt1IiwibmFtZSI6Im9ramFlb29rIn0.H1zc1zTN0tYJRUs2yttk1kGvJ23iT5IMb2jluECr95k


### 생성
POST http://localhost:8080/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMTU5NjI1LCJleHAiOjE3MDExNjE0MjUsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJElPdlVoOFJqdHRxMTRaSjhSYVBqUnVoN2FKa1ZDQVdMSHguSTl6UFJCbjl6dkZHOVg1Ykt1IiwibmFtZSI6Im9ramFlb29rIn0.TVvMcujy3_EQDJQcg0CXFVeQpJ5_rF0V83tvcs84dx4
Content-Type: application/json

{
  "roomTypeId": 11430,
  "accommodationId": 142785,
  "guestNumber": 1,
  "checkIn": "20231120",
  "checkOut": "20231123",
  "keyword": "가락관광호텔",
  "areaCode": "SEOUL"
}