### mock조회
GET http://localhost:8080/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMCIsImlhdCI6MTcwMDc1OTM0NiwiZXhwIjoxNzAwNzYxMTQ2LCJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIn0.pUeMo5RdX7o4oilaxmxjyE99OhLjyYTHlKmJDgIU4gw

### mock삭제
DELETE http://localhost:8080/carts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMCIsImlhdCI6MTcwMDc1OTM0NiwiZXhwIjoxNzAwNzYxMTQ2LCJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIn0.pUeMo5RdX7o4oilaxmxjyE99OhLjyYTHlKmJDgIU4gw


### mock생성
POST http://localhost:8080/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMCIsImlhdCI6MTcwMDc1OTM0NiwiZXhwIjoxNzAwNzYxMTQ2LCJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIn0.pUeMo5RdX7o4oilaxmxjyE99OhLjyYTHlKmJDgIU4gw
Content-Type: application/json

{
  "roomId": 1,
  "guestNumber": 1,
  "checkIn": "2023-11-20 15:00",
  "checkOut": "2023-11-21 11:00"
}


### 조회
GET http://localhost:8080/temp/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDI0ODc4LCJleHAiOjE3MDEwMjY2NzgsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20ifQ.Za4KVPygVdUibp-tJzymP2HRRq-AtFIAGZ5A1bHwSRI

### 삭제
DELETE http://localhost:8080/temp/carts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDI0ODc4LCJleHAiOjE3MDEwMjY2NzgsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20ifQ.Za4KVPygVdUibp-tJzymP2HRRq-AtFIAGZ5A1bHwSRI


### 생성
POST http://localhost:8080/temp/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDI0ODc4LCJleHAiOjE3MDEwMjY2NzgsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20ifQ.Za4KVPygVdUibp-tJzymP2HRRq-AtFIAGZ5A1bHwSRI
Content-Type: application/json

{
  "roomTypeId": 11430,
  "accommodationId": 142785,
  "guestNumber": 1,
  "checkIn": "2023-11-20",
  "checkOut": "2023-11-21"
}