### 조회
GET http://localhost:8080/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyNjMxNzQzLCJqdGkiOiJhYWZlNDFkOC03ZWI5LTQzOTgtOWQ3Mi1jNGMwN2IyZWYwMTkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDI2MzE4MDN9.anLVI75u94NC1G8PiUkCLRy2W5q97_ayBDIyywKaDuQ

### 삭제
DELETE http://localhost:8080/carts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyNjMxNzQzLCJqdGkiOiJhYWZlNDFkOC03ZWI5LTQzOTgtOWQ3Mi1jNGMwN2IyZWYwMTkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDI2MzE4MDN9.anLVI75u94NC1G8PiUkCLRy2W5q97_ayBDIyywKaDuQ


### 생성
POST http://localhost:8080/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyNjMxNzQzLCJqdGkiOiJhYWZlNDFkOC03ZWI5LTQzOTgtOWQ3Mi1jNGMwN2IyZWYwMTkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDI2MzE4MDN9.anLVI75u94NC1G8PiUkCLRy2W5q97_ayBDIyywKaDuQ
Content-Type: application/json

{
  "roomTypeId": 11430,
  "accommodationId": 142785,
  "guestNumber": 1,
  "checkIn": "20231216",
  "checkOut": "20231218",
  "keyword": "가락관광호텔",
  "areaCode": "SEOUL"
}