### 에약 번호로 예약한 숙소 조회
GET http://localhost:8080/reservation-rooms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ2Nzc3LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDY4Mzd9.8qqb9j0x7TP872Da_RV_V5oSe_7LUNHxTg4EhOCQWjM

### 예약 취소
DELETE http://localhost:8080/reservation-rooms?reservationId=1&reservationRoomId=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDY2NzQyLCJleHAiOjE3MDEwNjg1NDIsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJHdpZjd6bWlYUGY3TkNUQ3ZvNlM4ZC5NdG5VMHZNenJRUVBjN1piblpZN2IvN3FQaVo4T1BpIiwibmFtZSI6Im9ramFlb29rIn0.Gwmp4rbynlp2nJNCfTcyJA5AzCVmnD_4LkXS84FvEGg