### 예약 생성1
POST http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ2Nzc3LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDY4Mzd9.8qqb9j0x7TP872Da_RV_V5oSe_7LUNHxTg4EhOCQWjM

{
  "paymentType": "CARD",
  "reservationRooms" : [
    {
      "accommodationId": 142785,
      "accommodationName": "가락관광호텔",
      "areaCode": "SEOUL",
      "roomTypeId": 11430,
      "checkIn": "20250101",
      "checkOut": "20250103",
      "guestNumber": 2
    }
  ]
}

### 예약 생성2
POST http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ2Nzc3LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDY4Mzd9.8qqb9j0x7TP872Da_RV_V5oSe_7LUNHxTg4EhOCQWjM

{
  "paymentType": "CARD",
  "reservationRooms" : [
    {
      "accommodationId": 819849,
      "accommodationName": "킹모텔(구 호텔킹)",
      "areaCode": "GYEONGBUK",
      "roomTypeId": 823,
      "checkIn": "20250101",
      "checkOut": "20250103",
      "guestNumber": 2
    }
  ]
}

### 예약 생성 장바구니
POST http://localhost:8080/reservations/from-cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ3Njc5LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDc3Mzl9.n7bxTwr3d4imSS9ryjkVez2OOrQZ5mXhu-WbEMmNVqk

{
  "paymentType": "CARD",
  "cardIds": [3,4],
  "reservationRooms" : [
    {
      "accommodationId": 142785,
      "accommodationName": "가락관광호텔",
      "roomTypeId": 11430,
      "checkIn": "2022-01-01 14:00",
      "checkOut": "2022-01-02 11:00",
      "guestNumber": 2
    }
  ]
}



### 나의 예약 조회
GET http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ2Nzc3LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDY4Mzd9.8qqb9j0x7TP872Da_RV_V5oSe_7LUNHxTg4EhOCQWjM

### 예약 결제
POST http://localhost:8080/reservations/1/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDEwNDU4LCJleHAiOjE3MDEwMTIyNTgsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20ifQ.c5NKrqgVNj_CKLS2naYTx7p775vyAI1rMh_QwGRdv_Q

### 예약 취소
DELETE http://localhost:8080/reservations/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAwOTc5NTI2LCJleHAiOjE3MDA5ODEzMjYsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20ifQ.kcCZ2Kip4W6Ac_ZDbHP8iSp3oFsV3uzhcw066XGC6ks