### 예약 생성
POST http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDY2NzQyLCJleHAiOjE3MDEwNjg1NDIsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJHdpZjd6bWlYUGY3TkNUQ3ZvNlM4ZC5NdG5VMHZNenJRUVBjN1piblpZN2IvN3FQaVo4T1BpIiwibmFtZSI6Im9ramFlb29rIn0.Gwmp4rbynlp2nJNCfTcyJA5AzCVmnD_4LkXS84FvEGg

{
  "reservationRooms" : [
    {
      "accommodationId": 142785,
      "accommodationName": "가락관광호텔",
      "roomTypeId": 11430,
      "checkIn": "2022-01-01 14:00",
      "checkOut": "2022-01-02 11:00",
      "guestNumber": 2
    }
  ]
}



### 나의 예약 조회
GET http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDY2NzQyLCJleHAiOjE3MDEwNjg1NDIsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJHdpZjd6bWlYUGY3TkNUQ3ZvNlM4ZC5NdG5VMHZNenJRUVBjN1piblpZN2IvN3FQaVo4T1BpIiwibmFtZSI6Im9ramFlb29rIn0.Gwmp4rbynlp2nJNCfTcyJA5AzCVmnD_4LkXS84FvEGg


### 예약 결제
POST http://localhost:8080/reservations/1/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDY2NzQyLCJleHAiOjE3MDEwNjg1NDIsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJHdpZjd6bWlYUGY3TkNUQ3ZvNlM4ZC5NdG5VMHZNenJRUVBjN1piblpZN2IvN3FQaVo4T1BpIiwibmFtZSI6Im9ramFlb29rIn0.Gwmp4rbynlp2nJNCfTcyJA5AzCVmnD_4LkXS84FvEGg

### 예약 취소
DELETE http://localhost:8080/reservations/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDY2NzQyLCJleHAiOjE3MDEwNjg1NDIsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJHdpZjd6bWlYUGY3TkNUQ3ZvNlM4ZC5NdG5VMHZNenJRUVBjN1piblpZN2IvN3FQaVo4T1BpIiwibmFtZSI6Im9ramFlb29rIn0.Gwmp4rbynlp2nJNCfTcyJA5AzCVmnD_4LkXS84FvEGg