### 예약 생성
POST http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMTU2NTc2LCJleHAiOjE3MDExNTgzNzYsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJFNCbjZSQ3ZQdFQ2WW1vSVM0ZzU1dE8xTFBwRDJkSjJLbDBKcDRXT3k5RmhuNzNxdnNJQS51IiwibmFtZSI6Im9ramFlb29rIn0.HCiMHNhtW45GEFH2tbkihaeiqADBmehLfg2iGlIDuCE

{
  "paymentType": "CARD",
  "reservationRooms" : [
    {
      "accommodationId": 142785,
      "accommodationName": "가락관광호텔",
      "areaCode": "SEOUL",
      "roomTypeId": 11430,
      "checkIn": "2024-01-01T00:00",
      "checkOut": "2024-01-03T00:00",
      "guestNumber": 2
    }
  ]
}

### 예약 생성 장바구니
POST http://localhost:8080/reservations/from-cart
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMTE1OTk2LCJleHAiOjE3MDExMTc3OTYsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJHdpZjd6bWlYUGY3TkNUQ3ZvNlM4ZC5NdG5VMHZNenJRUVBjN1piblpZN2IvN3FQaVo4T1BpIiwibmFtZSI6Im9ramFlb29rIn0.G9xn5RFjHQZSnmTLfLtzmygz_HlUGxPyugnzpC06fQg

{
  "paymentType": "CARD",
  "cardIds": [3,4],
  "reservationRooms" : [
    {
      "accommodationId": 142785,
      "accommodationName": "가락관광호텔",
      "roomTypeId": 11430,
      "checkIn": "2022-01-01 14:00",
      "checkOut": "2022-01-02 11:00",
      "guestNumber": 2
    }
  ]
}



### 나의 예약 조회
GET http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMTExNjg1LCJleHAiOjE3MDExMTM0ODUsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IntiY3J5cHR9JDJhJDEwJERBdjM5S1c2RFVSVzN1djh4eEFQR2U3MEliUkJPLmg2QkNtWkk0TEw5RTd5WFhubjFMYS9XIiwibmFtZSI6Im9ramFlb29rIn0.ZlI9RVIpiEWw3IPhht0sKtSTdv63zX-W0BxBiYJqs2Q

### 예약 결제
POST http://localhost:8080/reservations/1/payment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAxMDEwNDU4LCJleHAiOjE3MDEwMTIyNTgsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20ifQ.c5NKrqgVNj_CKLS2naYTx7p775vyAI1rMh_QwGRdv_Q

### 예약 취소
DELETE http://localhost:8080/reservations/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzAwOTc5NTI2LCJleHAiOjE3MDA5ODEzMjYsImVtYWlsIjoib2tqYWVvb2s5OEBnbWFpbC5jb20ifQ.kcCZ2Kip4W6Ac_ZDbHP8iSp3oFsV3uzhcw066XGC6ks