### 회원 가입
POST http://localhost:8080/members/signup
Content-Type: application/json

{
"email": "okjaeook98@gmail.com",
"name": "okjaeook",
"password": "123456"
}

### 회원 로그인
POST http://localhost:8080/members/signin
Content-Type: application/json

{
  "email": "okjaeook98@gmail.com",
  "password": "123456"
}

### 회원 마이페이지 올바른 토큰
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ2Nzc3LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDY4Mzd9.8qqb9j0x7TP872Da_RV_V5oSe_7LUNHxTg4EhOCQWjM

#### 만료된 토큰
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ2Nzc3LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDY4Mzd9.8qqb9j0x7TP872Da_RV_V5oSe_7LUNHxTg4EhOCQWjM

#### 잘못된 jwt 포맷
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9asdeyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ2Nzc3LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDY4Mzd9.8qqb9j0x7TP872Da_RV_V5oSe_7LUNHxTg4EhOCQWjM

#### 발급처가 다른, 위/변조된 토큰
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAxOTM0MjUxLCJqdGkiOiIyZTY2Y2M5Mi0xNTU0LTQ2MjYtOGI1OC1lODQxNTZmNDQxYzQiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDE5MzQyNzF9.oSUUsQqkZxPs6w05X79gHja2vI_43XN0tnrsV9pJEGQ

#### 재발급된 코드로 마이페이지 접근
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAyMDQ3Njc5LCJqdGkiOiJhMWE2M2Q2OC00ZGI5LTQ2OWYtYjFjNy00M2RiZDU4OTk2NzkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDIwNDc3Mzl9.n7bxTwr3d4imSS9ryjkVez2OOrQZ5mXhu-WbEMmNVqk

#### 로그아웃
GET http://localhost:8080/members/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAxODgzMjQ2LCJqdGkiOiJkZjgxOTU2NC02ZmE5LTQxZDktYjNjYS0yMGVkMDgyOTdiMTkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDE4ODMyNjZ9.bIaaxnlaHiYBFnFcA7qlMc2hIgjqguVgjNfsSJSqCHg