### 회원 가입
POST http://localhost:8080/members/signup
Content-Type: application/json

{
"email": "okjaeook98@gmail.com",
"name": "okjaeook",
"password": "123456"
}

### 회원 로그인
POST http://localhost:8080/members/signin
Content-Type: application/json

{
  "email": "okjaeook98@gmail.com",
  "password": "123456"
}

### 회원 마이페이지 올바른 토큰
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAxOTQyMDg4LCJqdGkiOiI2MmFiODZlZi02MTgxLTRhNDQtOGMzMy01ZjFjOGZkNDIzMDgiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDE5NDIxNDh9.kmzSlmdSpZw64ssEp9EZaSB2iBFrcHnldzHtizvzlcA

#### 만료된 토큰
GET http://localhost:8080/members/mypage
Authorization: Bearer

#### 잘못된 jwt 포맷
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAxOTQwMTU3LCJqdGkiOiI0YWM1ZTY5MC03NWZmLTQ0MjYtYTM1ZC1iMWI2Y2Y3ODZmNzAiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDE5NDAyMTd9.YGqBbbXB1MmVIuPvisXGHR6kz-QJmpDmsb8kUDJkln8asd

#### 발급처가 다른, 위/변조된 토큰
GET http://localhost:8080/members/mypage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAxOTM0MjUxLCJqdGkiOiIyZTY2Y2M5Mi0xNTU0LTQ2MjYtOGI1OC1lODQxNTZmNDQxYzQiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDE5MzQyNzF9.oSUUsQqkZxPs6w05X79gHja2vI_43XN0tnrsV9pJEGQ

#### 로그아웃
GET http://localhost:8080/members/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9ramFlb29rOThAZ21haWwuY29tIiwiaWF0IjoxNzAxODgzMjQ2LCJqdGkiOiJkZjgxOTU2NC02ZmE5LTQxZDktYjNjYS0yMGVkMDgyOTdiMTkiLCJpc3MiOiJ5YmUubWluaS50cmF2ZWxzZXJ2ZXIiLCJleHAiOjE3MDE4ODMyNjZ9.bIaaxnlaHiYBFnFcA7qlMc2hIgjqguVgjNfsSJSqCHg